### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Reshy** [Snownee/Kiwi#42]
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

Kiwi-1.18.2-forge-6.1.2.jar

### Modloader version

40.1.68

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

Happens in a modpack environment, likely a weird conflict somewhere though I'm not where what's causing it.

Relevant parts of the log:
[05:16:52] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: kiwi, class snownee.kiwi.Kiwi
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.68.jar%23219!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.68.jar%23218!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.Multimap.put(Object, Object)" because "snownee.kiwi.Kiwi.moduleData" is null
	at snownee.kiwi.Kiwi.<init>(Kiwi.java:202) ~[Kiwi-1.18.2-forge-6.1.2.jar%23189!/:6.1.2]
	... 14 more

**Comment by Kalightortaio** [comment]
I'm having the same issue. I don't know if this a mod conflict with another mod, because I'm not seeing any other mods mentioned.
`[19:34:44] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: kiwi, class snownee.kiwi.Kiwi
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[javafmllanguage-1.18.2-40.1.52.jar%23289!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[fmlcore-1.18.2-40.1.52.jar%23288!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.common.collect.Multimap.put(Object, Object)" because "snownee.kiwi.Kiwi.moduleData" is null
	at snownee.kiwi.Kiwi.<init>(Kiwi.java:194) ~[Kiwi-1.18.2-forge-6.1.0.jar%23173!/:6.1.0]
	... 14 more`

**Comment by Kalightortaio** [comment]
Here is my full crash report
[crash-2022-07-28_19.35.07-fml.txt](https://github.com/Snownee/Kiwi/files/9227562/crash-2022-07-28_19.35.07-fml.txt)

**Comment by Snownee** [comment]
@Kalightortaio hmmm first, update kiwi

**Comment by Kalightortaio** [comment]
@Snownee This issue was found in 6.1.0, 6.1.1, and 6.1.2. 
I originally had 6.1.2 installed, and tried to backgrade to see if it was a recent update.

As much as I really enjoy your mods, I've since removed kiwi along with snow real magic and passable foliage.

I'm still leaning towards a mod conflict, as everything was working at around 200 mods. Adding several more mods broke several things, and as I was debugging each conflict, I just couldn't solve this one.

**Comment by Kalightortaio** [comment]
If @Reshy and I could compare mod lists, that may prove useful, unless this issue is occurring by itself... I haven't frankly tested that myself.

**Comment by Reshy** [comment]
I've altered my modlist since then, but I can see if I can replicate it again.

**Comment by Snownee** [comment]
seems to be an issue with Braincell API. I have fixed it in the latest version. if it still occurs, feel free to reopen this issue
